ECClaimSystem/Controllers/ECCoordinatorController.cs
using ECClaimSystem.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static ECClaimSystem.Models.Elements.ConstantsKey;

namespace ECClaimSystem.Controllers
{
    public class ECCoordinatorController : Controller
    {
        IECClaimRepository _ecClaimRepository;
        public ECCoordinatorController()
        {
            _ecClaimRepository = new ECClaimRepository();
        }
        // GET: ECManager
        public ActionResult Index()
        {
            if (Session["User"] != null)
            {
                return RedirectToAction("ViewListEC", "User");
            }
            return RedirectToAction("Login", "User");
        }

        public ActionResult ShowListECClaim()
        {
            List<ECClaim> lsClaim = Session["ListClaim"] as List<ECClaim>;
            List<Models.ECClaim> lsECClaim = new List<Models.ECClaim>();
            if (lsClaim == null || lsClaim.Count == 0)
            {
                ViewBag.Message = "There is no Ec claim";
            }
            else
            {
                lsECClaim = lsClaim.Select(x => new Models.ECClaim
                {
                    ClaimId = x.ClaimId,
                    User = new Models.User { UserId = x.UserId.Value },
                    Summary = x.Summary,
                    Situation = x.Situation,
                    EffectSituation = x.EffectSituation,
                    CircumstanceStartDate = x.CircumstanceStartDate,
                    CircumstanceEndDate = x.CircumstanceEndDate,
                    OutCome = x.OutCome.Value,
                    FinalClosureDate = x.FinalClosureDate,
                    SubmittedDate = x.SubmittedDate,
                    ClaimStatus = x.ClaimStatus,
                    DecisionStatus = x.DecisionStatus,
                    DecisionDate = x.DecisionDate.HasValue ? x.DecisionDate.Value : (DateTime?)null,
                    ProcessedUser = x.ProcessedUser,
                    HasEvidence = x.HasEvidence.Value,
                    Active = x.Active.Value
                }).ToList();
                ViewBag.Message = string.Format("Total: {0}", lsClaim.Count);
            }
            return View(lsECClaim);
        }

        public ActionResult Details(long id)
        {
            ECClaim ec = _ecClaimRepository.GetECClaimById(id);
            List<ECEvidence> lsEvidence = _ecClaimRepository.GetEvidencesByECClaim(id);
            Models.ECClaim claim = new Models.ECClaim();
            if (ec != null)
            {
                claim.ClaimId = ec.ClaimId;
                claim.User = new Models.User { UserId = ec.UserId.Value };
                claim.Summary = ec.Summary;
                claim.Situation = ec.Situation;
                claim.EffectSituation = ec.EffectSituation;
                claim.CircumstanceStartDate = ec.CircumstanceStartDate;
                claim.CircumstanceEndDate = ec.CircumstanceEndDate;
                claim.OutCome = ec.OutCome.Value;
                claim.FinalClosureDate = ec.FinalClosureDate;
                claim.SubmittedDate = ec.SubmittedDate;
                claim.ClaimStatus = ec.ClaimStatus;
                claim.DecisionStatus = ec.DecisionStatus;
                claim.DecisionDate = ec.DecisionDate.HasValue ? ec.DecisionDate.Value : (DateTime?)null;
                claim.ProcessedUser = ec.ProcessedUser;
                claim.HasEvidence = ec.HasEvidence.Value;
                claim.Active = ec.Active.Value;
            }
            Session["Evidences"] = lsEvidence;
            return View("Details", claim);
        }
        [HttpPost]

        public ActionResult AcceptOrDenyECClaim(Models.ECClaim model, int type)
        {

            User u = Session["User"] as User;
            ECClaim ec = new ECClaim
            {

                ClaimId = model.ClaimId,
                ClaimStatus = type == 1 ? (int)ClaimStatus.Processing : (int)ClaimStatus.Rejected,
                ProcessedUser = u.UserId
            };
            _ecClaimRepository.AcceptOrDenyECClaim(ec);
            return RedirectToAction("Details", new { id = model.ClaimId });


        }
        [HttpPost]
        public ActionResult UpdateDecision(int decisionstatus, long claimid)
        {
            _ecClaimRepository.UpdateDecision(decisionstatus, claimid);
            return Json("OK");
        }
        [HttpPost]
        public ActionResult SendMail(long id)
        {
            User u = Session["User"] as User;
           string response = _ecClaimRepository.SendMail(u, id);
            return Json(response);
        }
    }
}

ECClaimSystem/Views/ECCoordinator/Details.cshtml
@model ECClaimSystem.Models.ECClaim

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<ECEvidence> lsEvidence = new List<ECEvidence>();
    List<ECEvidence> lsEvidenceImage = new List<ECEvidence>();
    if (Session["Evidences"] != null)
    {
        lsEvidence = Session["Evidences"] as List<ECEvidence>;
        lsEvidenceImage = lsEvidence.Where(x => x.Type == (int)ECClaimSystem.Models.Elements.ConstantsKey.EvidenceType.Image).ToList();
    }
}

<p>
    @Html.ActionLink("Back to List", "ShowListECClaim")
</p>

    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <h2>Details</h2>
                <div>
                    
                    @using (Html.BeginForm("AcceptOrDenyECClaim","ECCoordinator",FormMethod.Post,new { @class= "form-horizontal form-label-left", @novalidate="", @id="formEC", @name="formEC" }))
                    {
                        <div>
                            <input type="text" name="claimId" value="@Model.ClaimId" style="visibility:hidden" />
                        </div>
                        <div class="form-group">

                            <label class="col-md-3 col-sm-3 col-xs-12">
                                Summary
                            </label>


                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.DisplayFor(model => model.Summary)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 col-sm-3 col-xs-12">
                                Situation
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.DisplayFor(model => model.Situation)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 col-sm-3 col-xs-12">
                                Result
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.DisplayFor(model => model.EffectSituation)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 col-sm-3 col-xs-12">
                                Duration
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.DisplayFor(model => model.CircumstanceStartDate, "0:dd/MM/yyyy") - @Html.DisplayFor(model => model.CircumstanceEndDate, "0:dd/MM/yyyy")
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 col-sm-3 col-xs-12">
                                Submitted Date - Final Closure Date - Result Date
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.DisplayFor(model => model.SubmittedDate, "0:dd/MM/yyyy") - @Html.DisplayFor(model => model.FinalClosureDate, "0:dd/MM/yyyy") -
                                @if (Model.DecisionDate != null)
                                {
                                    @Html.DisplayFor(model => model.DecisionDate, "0:dd/MM/yyyy")
                                }
                                else
                                {
                                    <span>Not yet</span>
                                }

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 col-sm-3 col-xs-12">
                                Claim Status
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @if (Model.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Pending)
                                {
                                    <span>Pending</span>
                                }
                                @if (Model.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Processing)
                                {
                                    <span>Processing</span>
                                }
                                @if (Model.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Processed)
                                {
                                    <span>Processed</span>
                                }
                                @if (Model.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Rejected)
                                {
                                    <span>Rejected</span>
                                }
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 col-sm-3 col-xs-12">
                                Decision
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @if (Model.DecisionStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.DecisionStatus.Pending)
                                {
                                    <span>Pending</span>
                                }
                                @if (Model.DecisionStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.DecisionStatus.Fail)
                                {
                                    <span>Fail</span>
                                }
                                @if (Model.DecisionStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.DecisionStatus.Success)
                                {
                                    <span>Success</span>
                                }

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 col-sm-3 col-xs-12">
                                Has Evidence
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.DisplayFor(model => model.HasEvidence)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 col-sm-3 col-xs-12">
                                Evidences
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">

                                @for (int i = 0; i < lsEvidenceImage.Count; i++)
                                {

                                    if (i % 3 == 0)
                                    {
                                        <div class="clearfix"></div>
                                        <div class="row">
                                            <div class="col-md-4 col-sm-4 col-xs-12">
                                                <div class="x_panel tile">
                                                    <img src='../../File/Evidence/@lsEvidenceImage[i].EvidenceName' alt="image" width="200" />
                                                </div>
                                            </div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="col-md-4 col-sm-4 col-xs-12">
                                            <div class="x_panel tile">
                                                <img src='../../File/Evidence/@lsEvidenceImage[i].EvidenceName' alt="image" width="200" />
                                            </div>
                                        </div>
                                    }
                                }
                                @foreach (var item in lsEvidence.Where(x => x.Type == (int)ECClaimSystem.Models.Elements.ConstantsKey.EvidenceType.Pdf).ToList())
                                {
                                    <iframe src="../../File/Evidence/b9970d39bc844c3baf9ac49019875467.pdf" style="width: 100%;height: 500px;border: solid 1px;"></iframe>
                                }
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                <button id="accept" type="button" class="btn btn-success" value="Accept" onclick="acceptClaim();">Accept</button>
                                <button id="deny" type="button" class="btn btn-success" value="Deny" onclick="denyClaim();">Deny</button>
                            </div>
                        </div>
                    }
               

                </div>
            </div>
        </div>
    </div>
<script>
    function acceptClaim() {
        $("#formEC").attr("action", "/ECCoordinator/AcceptOrDenyECClaim?type=1");
        document.formEC.submit();
    }
    function denyClaim() {
        $("#formEC").attr("action", "/ECCoordinator/AcceptOrDenyECClaim?type=2");
        document.formEC.submit();
    }
</script>

ECClaimSystem/Views/ECCoordinator/ShowListECClaim.cshtml
@model IEnumerable<ECClaimSystem.Models.ECClaim>

@{
    ViewBag.Title = "ShowListECClaim";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<span class="text-danger">@ViewBag.Message</span>
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_content">
            @if (Model.Count() > 0)
            {
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr>
                                <th class="column-title">
                                    @Html.DisplayNameFor(model => model.Summary)
                                </th>
                                <th class="column-title">
                                    @Html.DisplayNameFor(model => model.Situation)
                                </th>
                                <th class="column-title">
                                    Effect
                                </th>
                                <th class="column-title">
                                    Submitted Date
                                </th>
                                <th class="column-title">
                                    @Html.ActionLink("Final Closure Date", "SortECClaim", "User", new { type = (int)ECClaimSystem.Models.Elements.ConstantsKey.SortType.ClosureDate }, new { @style = "color:white" })
                                </th>
                                <th class="column-title">
                                    Claim Status
                                </th>
                                <th class="column-title">
                                    Decision
                                </th>
                                <th class="column-title">
                                    @Html.DisplayNameFor(model => model.Active)
                                </th>
                                <th>

                                </th>
                            </tr>

                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {

                                <tr class="even pointer">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Summary)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Situation)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EffectSituation)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SubmittedDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FinalClosureDate)
                                    </td>
                                    <td>
                                        @if (item.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Pending)
                                        {
                                            <span>Pending</span>
                                        }
                                        @if (item.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Processing)
                                        {
                                            <span>Processing</span>
                                        }
                                        @if (item.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Processed)
                                        {
                                            <span>Processed</span>
                                        }
                                        @if (item.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Rejected)
                                        {
                                            <span>Rejected</span>
                                        }
                                    </td>
                                    <td>
                                        @if (item.HasEvidence == true && item.FinalClosureDate.Value.AddDays(item.OutCome) > DateTime.Now)
                                        {
                                            @Html.DropDownListFor(modelItem => item.DecisionStatus, EnumHelper.GetSelectList(typeof(ECClaimSystem.Models.Elements.ConstantsKey.DecisionStatus), (ECClaimSystem.Models.Elements.ConstantsKey.DecisionStatus)item.DecisionStatus), "Select Decision", new { @class = "form-control", onchange = "UpdateDecision(this," + @item.ClaimId + ")" })


                                        }
                                        else
                                        {
                                            @Html.DropDownListFor(modelItem => item.DecisionStatus, EnumHelper.GetSelectList(typeof(ECClaimSystem.Models.Elements.ConstantsKey.DecisionStatus), (ECClaimSystem.Models.Elements.ConstantsKey.DecisionStatus)item.DecisionStatus), "Select Decision", new { @class = "form-control", @style="disabled"})
                                        }

                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Active)
                                    </td>
                                    <td>
                                        @if (item.HasEvidence == true && item.FinalClosureDate.Value.AddDays(item.OutCome) > DateTime.Now)
                                        {
                                            @Html.ActionLink("Details", "Details", new { id = item.ClaimId })

                                        }
                                        | @Html.ActionLink("Send Email", null, new { onclick = "SendMail("+@item.ClaimId+")" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

            }

        </div>
    </div>
</div>
<script>
    function UpdateDecision(item, id) {
        var value = $(item).val();
        var data = { decisionstatus: value, claimid: id };
        $.post("/ECCoordinator/UpdateDecision", data, function (response) {

        })
    }
    function SendMail(id) {
        var data = {id : id};
        $.post("/ECCoordinator/SendMail", data, function (response) {
            alert(response);
        })
    }
</script>