ECClaimSystem/Controllers/AdministratorController.cs
using ECClaimSystem.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static ECClaimSystem.Models.Elements.ConstantsKey;

namespace ECClaimSystem.Controllers
{
    public class AdministratorController : Controller
    {
        IECClaimRepository _ecClaimRepository;
        public AdministratorController()
        {
            _ecClaimRepository = new ECClaimRepository();
        }
        // GET: Administrator
        public ActionResult Index()
        {
            if (Session["User"] != null)
            {
                List<Faculty> lsFaculty = _ecClaimRepository.GetAllFaculty();
                Session["Faculties"] = lsFaculty;
                return RedirectToAction("ViewListEC", "User");
            }
            return RedirectToAction("Login", "User");
        }

        public ActionResult ShowListECClaim()
        {
            List<ECClaim> lsClaim = Session["ListClaim"] as List<ECClaim>;
            List<Models.ECClaim> lsECClaim = new List<Models.ECClaim>();
            if (lsClaim == null || lsClaim.Count == 0)
            {
                ViewBag.Message = "There is no Ec claim";
            }
            else
            {
                lsECClaim = lsClaim.Select(x => new Models.ECClaim
                {
                    ClaimId = x.ClaimId,
                    User = new Models.User { UserId = x.UserId.Value },
                    Summary = x.Summary,
                    Situation = x.Situation,
                    EffectSituation = x.EffectSituation,
                    CircumstanceStartDate = x.CircumstanceStartDate,
                    CircumstanceEndDate = x.CircumstanceEndDate,
                    OutCome = x.OutCome.Value,
                    FinalClosureDate = x.FinalClosureDate,
                    SubmittedDate = x.SubmittedDate,
                    ClaimStatus = x.ClaimStatus,
                    DecisionStatus = x.DecisionStatus,
                    DecisionDate = x.DecisionDate.HasValue ? x.DecisionDate.Value : (DateTime?)null,
                    ProcessedUser = x.ProcessedUser,
                    HasEvidence = x.HasEvidence.Value,
                    Active = x.Active.Value
                }).ToList();

            }
            return View(lsECClaim);
        }
        public ActionResult Details(long id)
        {
            ECClaim ec = _ecClaimRepository.GetECClaimById(id);
            Models.ECClaim claim = new Models.ECClaim();
            if (ec != null)
            {
                claim.ClaimId = ec.ClaimId;
                claim.User = new Models.User { UserId = ec.UserId.Value };
                claim.Summary = ec.Summary;
                claim.Situation = ec.Situation;
                claim.EffectSituation = ec.EffectSituation;
                claim.CircumstanceStartDate = ec.CircumstanceStartDate;
                claim.CircumstanceEndDate = ec.CircumstanceEndDate;
                claim.OutCome = ec.OutCome.Value;
                claim.FinalClosureDate = ec.FinalClosureDate;
                claim.SubmittedDate = ec.SubmittedDate;
                claim.ClaimStatus = ec.ClaimStatus;
                claim.DecisionStatus = ec.DecisionStatus;
                claim.DecisionDate = ec.DecisionDate.HasValue ? ec.DecisionDate.Value : (DateTime?)null;
                claim.ProcessedUser = ec.ProcessedUser;
                claim.HasEvidence = ec.HasEvidence.Value;
                claim.Active = ec.Active.Value;
            }
            return View("Details", claim);
        }
        [HttpPost]
        public ActionResult ChangeActiveStatusOfECClaim(bool value, long claimId)
        {
            string response = _ecClaimRepository.ChangeActiveOfECClaim(claimId, value);
            return Json(response);
        }

        public ActionResult GetAllUser()
        {
            if (Session["User"] != null)
            {
                List<User> lsUser = _ecClaimRepository.GetAllUser();
                List<Models.User> ls = new List<Models.User>();
                if (lsUser != null)
                {
                    ls = lsUser.Select(x => new Models.User
                    {
                        AccountId = x.AccountId,
                        Active = x.Active.Value,
                        Address = x.Address,
                        BirthDay = x.BirthDay,
                        Email = x.Email,
                        Gender = x.Gender,
                        Phone = x.Phone,
                        UserFullName = x.UserFullName,
                        UserId = x.UserId,
                        Role = new Models.Role { RoleName = x.Role.RoleName, RoleId = x.Role.RoleId, Active = x.Role.Active.Value }

                    }).ToList();
                }
                else
                {
                    ViewBag.Message = "There is no user";
                }
                return View(ls);
            }
            return RedirectToAction("Login", "User");
        }

        [HttpPost]
        public ActionResult ChangeActiveStatusUser(long userId, bool value)
        {
            string response = _ecClaimRepository.ChangeActiveStatusUser(userId, value);
            return Json(response);
        }

        public ActionResult Edit(long id)
        {
            User u = _ecClaimRepository.GetUserById(id);
            Models.User user = new Models.User();
            if (u != null)
            {
                user.Address = u.Address;
                user.BirthDay = u.BirthDay;
                user.Email = u.Email;
                user.FacultyId = u.FacultyId.HasValue ? u.FacultyId.Value : 0;
                user.Gender = u.Gender;
                user.Phone = u.Phone;
                user.RoleId = u.RoleId;
                user.UserFullName = u.UserFullName;
                user.UserId = u.UserId;
            }
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult UpdateUser(Models.User model)
        {
            if (ModelState.IsValid)
            {
                int result = _ecClaimRepository.UpdateUser(model);
                if (result == 0)
                {
                    ViewBag.Message = "Check information again, at least your email";
                }
                else
                {
                    return RedirectToAction("Edit", new { id = model.UserId });
                }
            }
            return View("Edit", model);
        }

        public ActionResult CancelUpdateUser()
        {
            return RedirectToAction("GetAllUser");
        }

        public ActionResult CreateUser()
        {
            if (Session["User"] != null)
            {
                return View("CreateUser", new Models.User());
            }
            return RedirectToAction("Login", "User");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult CreateNewUser(Models.User model)
        {
            if (ModelState.IsValid)
            {
                string[] SplitStrings = model.Email.Split('@');
                model.AccountId = SplitStrings[0];
                model.Password = model.AccountId;
                int result = _ecClaimRepository.InsertUser(model);
                if (result == 0)
                {
                    ViewBag.Message = "Check information again";
                }
                else
                {
                    return RedirectToAction("GetAllUser");
                }
            }
            return View("CreateUser", model);
        }

        public ActionResult GetAllSetting()
        {
            if (Session["User"] != null)
            {
                List<Setting> lsSetting = _ecClaimRepository.GetAllSetting();
                List<Models.Setting> ls = new List<Models.Setting>();
                if (lsSetting != null)
                {
                    ls = lsSetting.Select(x => new Models.Setting
                    {
                        Active = x.Active.Value,
                        Id = x.Id,
                        Key = x.Key,
                        Value = x.Value
                    }).ToList();
                }
                else
                {
                    ViewBag.Message = "There is no setting";
                }
                return View("Setting", ls);
            }
            return RedirectToAction("Login", "User");
        }

        [HttpPost]
        public ActionResult SubmitSetting(int? id, string key, string value)
        {
            if (key == null || key == "")
            {
                ViewBag.ErrorKey = "This field cannot be empty";
                return RedirectToAction("GetAllSetting");
            }
            if (_ecClaimRepository.GetSettingByKey(key) != null && !id.HasValue)
            {
                ViewBag.ErrorKey = "This key existed";
                return RedirectToAction("GetAllSetting");
            }
            _ecClaimRepository.UpdateOrInsertSetting(id, key, value);
            Session.Remove("Setting");
            return RedirectToAction("GetAllSetting");
        }

        public ActionResult EditSetting(int id)
        {
            Setting setting = _ecClaimRepository.GetSettingById(id);
            Session["Setting"] = setting;
            return RedirectToAction("GetAllSetting");
        }

        public ActionResult CancelCreateSetting()
        {
            Session.Remove("Setting");
            return RedirectToAction("GetAllSetting");
        }
        [HttpPost]
        public ActionResult ChangeActiveStatusSetting(bool value, int id)
        {
            string response = _ecClaimRepository.ChangeActiveSetting(id, value);
            return Json(response);
        }

        public ActionResult CancelCreateUser()
        {
            return RedirectToAction("CreateUser");
        }
        [HttpPost]

ECClaimSystem/Views/Shared/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @Styles.Render("~/Content/Admin/css")
</head>

<body class="login">
    <form method="post" action="@Url.Action("LoginAccount","User")">
        <div>
            <a class="hiddenanchor" id="signup"></a>
            <a class="hiddenanchor" id="signin"></a>
            <div class="login_wrapper">
                <div class="animate form login_form">
                    <section class="login_content">
                        <form>
                            <h1>Login Form</h1>
                            <div class="alert-error">
                                @ViewBag.Error
                            </div>
                            <div>
                                <input type="text" class="form-control" placeholder="Username" name="username" id="txtUserName" required="" />
                            </div>
                            <br />
                            <div>
                                <input type="password" class="form-control" placeholder="Password" name="password" id="txtPassword" required="" />
                            </div>
                            <br />
                            <div>
                                @*<a class="btn btn-default submit" href="index.html">Log in</a>*@
                                <input type="submit" name="btnLogin" class="btn btn-default submit" value="Login" style="text-align:center; float:none; margin-left:0" />
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </section>
                </div>

            </div>
        </div>
    </form>

</body>
</html>

ECClaimSystem/Views/Shared/_Layout.cshtml
@{
    ECClaimSystem.User u = new ECClaimSystem.User();
    if (Session["User"] != null)
    {
        u = Session["User"] as ECClaimSystem.User;
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EC Claim System</title>
    @Styles.Render("~/Content/Admin/css")

    <script src="~/Content/Scripts/bootstrap.min.js"></script>
    <script src="~/Content/Scripts/custom.min.js"></script>
    <script src="~/Content/Scripts/daterangepicker.js"></script>
    <script src="~/Content/Scripts/icheck.min.js"></script>
    <script src="~/Content/Scripts/jquery.min.js"></script>
    <script src="~/Content/Scripts/moment.min.js"></script>
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="#" class="site_title"><span>EC Claim System!</span></a>
                    </div>
                    <div class="clearfix"></div>
                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2>@u.UserFullName</h2>
                        </div>
                    </div>
                    <!-- /menu profile quick info -->
                    <br />
                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <ul class="nav side-menu">
                                @if (u.RoleId == (int)ECClaimSystem.Models.Elements.ConstantsKey.Role.Administrator)
                                {
                                    <li>
                                        @Html.ActionLink("EC Claims", "Index", "Administrator")
                                    </li>
                                    <li>
                                        @Html.ActionLink("User", "GetAllUser", "Administrator")
                                    </li>
                                    <li>
                                        @Html.ActionLink("Setting", "GetAllSetting", "Administrator")
                                    </li>
                                    <li>
                                        @Html.ActionLink("Statistics", "RedirectStatisticPage", "Administrator")
                                    </li>
                                    <li>
                                        @Html.ActionLink("Reports", "RedirectReportPage", "Administrator")
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                    <!-- /sidebar menu -->
                    <!-- /menu footer buttons -->
                    <!-- /menu footer buttons -->
                </div>
            </div>
            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">

                        </div>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                              @Html.ActionLink("Logout", "Logout", "User",null, new { @class="user-profile dropdown-toggle"})  
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main" style="min-height:1000px !important">
                @RenderBody()
            </div>
            <!-- /page content -->
            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>

</body>
</html>

ECClaimSystem/Views/Shared/_LayoutStudent.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EC Claim System</title>
    @Styles.Render("~/Content/Admin/css")

    <script src="~/Content/Scripts/bootstrap.min.js"></script>
    <script src="~/Content/Scripts/custom.min.js"></script>
    <script src="~/Content/Scripts/daterangepicker.js"></script>
    <script src="~/Content/Scripts/icheck.min.js"></script>
    <script src="~/Content/Scripts/jquery.min.js"></script>
    <script src="~/Content/Scripts/moment.min.js"></script>
    <script src="~/Content/Scripts/dataTables.bootstrap.min.js"></script>
</head>
<body class="nav-md" style="background: #EDEDED !important">
    <div class="container body">
        <div class="main_container">
            <div style="float:right; margin-right:50px;">
                @Html.ActionLink("Logout", "Logout", "User")
            </div>
            <!-- top navigation -->
            <!-- /top navigation -->
            <!-- page content -->
            
                @RenderBody()
           
            <!-- /page content -->
            <!-- footer content -->
         
            <!-- /footer content -->
        </div>
    </div>

</body>
</html>