ECClaimSystem/Controllers/ECManagerController.cs
using ECClaimSystem.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECClaimSystem.Controllers
{
    public class ECManagerController : Controller
    {
        IECClaimRepository _ecClaimRepository;
        public ECManagerController()
        {
            _ecClaimRepository = new ECClaimRepository();
        }
        // GET: ECManager
        public ActionResult Index()
        {
            if (Session["User"] != null)
            {
                List<Faculty> lsFaculty = _ecClaimRepository.GetAllFaculty();
                Session["Faculties"] = lsFaculty;
                return RedirectToAction("ViewListEC", "User");
            }
            return RedirectToAction("Login", "User");
        }

        public ActionResult ShowListECClaim()
        {
            List<ECClaim> lsClaim = Session["ListClaim"] as List<ECClaim>;
            List<Models.ECClaim> lsECClaim = new List<Models.ECClaim>();
            if (lsClaim == null || lsClaim.Count == 0)
            {
                ViewBag.Message = "There is no Ec claim";
            }
            else
            {
                lsECClaim = lsClaim.Select(x => new Models.ECClaim
                {
                    ClaimId = x.ClaimId,
                    User = new Models.User { UserId = x.UserId.Value },
                    Summary = x.Summary,
                    Situation = x.Situation,
                    EffectSituation = x.EffectSituation,
                    CircumstanceStartDate = x.CircumstanceStartDate,
                    CircumstanceEndDate = x.CircumstanceEndDate,
                    OutCome = x.OutCome.Value,
                    FinalClosureDate = x.FinalClosureDate,
                    SubmittedDate = x.SubmittedDate,
                    ClaimStatus = x.ClaimStatus,
                    DecisionStatus = x.DecisionStatus,
                    DecisionDate = x.DecisionDate.HasValue ? x.DecisionDate.Value : (DateTime?)null,
                    ProcessedUser = x.ProcessedUser,
                    HasEvidence = x.HasEvidence.Value,
                    Active = x.Active.Value
                }).ToList();
                ViewBag.Message = string.Format("Total: {0}", lsClaim.Count);
            }
            return View(lsECClaim);
        }

        public ActionResult Details(long id)
        {
            ECClaim ec = _ecClaimRepository.GetECClaimById(id);
            Models.ECClaim claim = new Models.ECClaim();
            if (ec != null)
            {
                claim.ClaimId = ec.ClaimId;
                claim.User = new Models.User { UserId = ec.UserId.Value };
                claim.Summary = ec.Summary;
                claim.Situation = ec.Situation;
                claim.EffectSituation = ec.EffectSituation;
                claim.CircumstanceStartDate = ec.CircumstanceStartDate;
                claim.CircumstanceEndDate = ec.CircumstanceEndDate;
                claim.OutCome = ec.OutCome.Value;
                claim.FinalClosureDate = ec.FinalClosureDate;
                claim.SubmittedDate = ec.SubmittedDate;
                claim.ClaimStatus = ec.ClaimStatus;
                claim.DecisionStatus = ec.DecisionStatus;
                claim.DecisionDate = ec.DecisionDate.HasValue ? ec.DecisionDate.Value : (DateTime?)null;
                claim.ProcessedUser = ec.ProcessedUser;
                claim.HasEvidence = ec.HasEvidence.Value;
                claim.Active = ec.Active.Value;
            }
            return View("Details", claim);
        }
        [HttpPost]
        public ActionResult FilterECClaimByFaculty(int facultyId)
        {
            List<ECClaim> lsClaim = new List<ECClaim>();
            if (Session["ListClaim"] != null)
            {
                lsClaim = _ecClaimRepository.GetECClaimsByFaculty(facultyId);
                Session["ListClaim"] = lsClaim;
            }
            return RedirectToAction("ShowListECClaim");
        }
    }
}

ECClaimSystem/Views/ECManager/Details.cshtml
@model ECClaimSystem.Models.ECClaim

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    @Html.ActionLink("Back to List", "ShowListECClaim")
</p>
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_content">
            <h2>Details</h2>
            <div>
                <form id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left" novalidate="">

                    <div class="form-group">

                        <label class="col-md-3 col-sm-3 col-xs-12">
                            Summary
                        </label>


                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.DisplayFor(model => model.Summary)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-sm-3 col-xs-12">
                            Situation
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.DisplayFor(model => model.Situation)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-sm-3 col-xs-12">
                            Result
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.DisplayFor(model => model.EffectSituation)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-sm-3 col-xs-12">
                            Duration
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.DisplayFor(model => model.CircumstanceStartDate, "0:dd/MM/yyyy") - @Html.DisplayFor(model => model.CircumstanceEndDate, "0:dd/MM/yyyy")
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-sm-3 col-xs-12">
                            Submitted Date - Final Closure Date - Result Date
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.DisplayFor(model => model.SubmittedDate, "0:dd/MM/yyyy") - @Html.DisplayFor(model => model.FinalClosureDate, "0:dd/MM/yyyy") - 
                            @if (Model.DecisionDate != null)
                            {
                                @Html.DisplayFor(model => model.DecisionDate, "0:dd/MM/yyyy")
                            }
                            else
                            {
                                <span>Not yet</span>
                            }

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-sm-3 col-xs-12">
                            Claim Status
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @if (Model.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Pending)
                            {
                                <span>Pending</span>
                            }
                            @if (Model.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Accepted)
                            {
                                <span>Accepted</span>
                            }
                            @if (Model.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Processed)
                            {
                                <span>Processed</span>
                            }
                            @if (Model.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Rejected)
                            {
                                <span>Rejected</span>
                            }
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-sm-3 col-xs-12">
                            Decision
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @if (Model.DecisionStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.DecisionStatus.Pending)
                            {
                                <span>Pending</span>
                            }
                            @if (Model.DecisionStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.DecisionStatus.Fail)
                            {
                                <span>Fail</span>
                            }
                            @if (Model.DecisionStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.DecisionStatus.Success)
                            {
                                <span>Success</span>
                            }

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 col-sm-3 col-xs-12">
                            Has Evidence
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.DisplayFor(model => model.HasEvidence)
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

ECClaimSystem/Views/ECManager/ShowListECClaim.cshtml
@model IEnumerable<ECClaimSystem.Models.ECClaim>

@{
    ViewBag.Title = "ShowListECClaim";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Faculty> lsFaculty = new List<Faculty>();
    if (Session["Faculties"] != null)
    {
        lsFaculty = Session["Faculties"] as List<Faculty>;
    }
}
@using (Html.BeginForm("FilterECClaimByFaculty", "ECManager", FormMethod.Post, new { id = "formFaculty", name = "formFaculty" }))
{
    <div class="form-group">
        @Html.DropDownList("Faculties", new SelectList(lsFaculty, "FacultyId", "FacultyName"), "Select Faculty", new { @class = "form-control", onchange = "SortByFaculty(this);" })

    </div>

}


<span class="text-danger">@ViewBag.Message</span>
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_content">
            @if (Model.Count() > 0)
            {
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr>
                                <th class="column-title">
                                    @Html.DisplayNameFor(model => model.Summary)
                                </th>
                                <th class="column-title">
                                    @Html.DisplayNameFor(model => model.Situation)
                                </th>
                                <th class="column-title">
                                    Effect
                                </th>
                                <th class="column-title">
                                    Submitted Date
                                </th>
                                <th class="column-title">
                                    @Html.ActionLink("Final Closure Date", "SortECClaim", "User", new { type = (int)ECClaimSystem.Models.Elements.ConstantsKey.SortType.ClosureDate }, new { @style = "color:white" })
                                </th>
                                <th class="column-title">
                                    Claim Status
                                </th>
                                <th class="column-title">
                                    @Html.DisplayNameFor(model => model.Active)
                                </th>
                                <th>

                                </th>
                            </tr>

                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {

                                <tr class="even pointer">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Summary)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Situation)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EffectSituation)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SubmittedDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FinalClosureDate)
                                    </td>
                                    <td>
                                        @if (item.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Pending)
                                        {
                                            <span>Pending</span>
                                        }
                                        @if (item.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Accepted)
                                        {
                                            <span>Accepted</span>
                                        }
                                        @if (item.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Processed)
                                        {
                                            <span>Processed</span>
                                        }
                                        @if (item.ClaimStatus == (int)ECClaimSystem.Models.Elements.ConstantsKey.ClaimStatus.Rejected)
                                        {
                                            <span>Rejected</span>
                                        }
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Active)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Details", "Details", new { id = item.ClaimId})
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

            }

        </div>
    </div>
</div>
<script>
    function SortByFaculty(item) {
        var value = $(item).val();
        $("#formFaculty").attr("action", "/ECManager/FilterECClaimByFaculty?facultyId=" + value);
        document.formFaculty.submit();
    }
</script>